version: '3'

includes:
  env: ./build/EnvTaskfile.yml
  proto: ./build/ProtoTaskfile.yml
  lint: ./build/LintTaskFile.yml
  test: ./build/TestTaskFile.yml

silent: true

tasks:
  build:
    cmds:
      - echo 'Building project grpc-server...'
      - go build -v ./...
      - echo '######################################'

  run-server:
    cmds:
      - echo 'Running server for grpc-server...'
      - go run server_main.go
      - echo '######################################'

  run-client:
    cmds:
      - echo 'Running client for grpc-server...'
      - go run cmd/list_students_main.go
      - echo '######################################'

  all:
    cmds:
      - task: env:display-variables
      - task: proto:generate-proto
      #- task: lint:lint-report
      #- task: lint:lint-fix
      #- task: test:execute-tests
      - task: build
      - echo 'All tasks have been completed!!!'
      - echo '######################################'